/** Semantic token names shown on the /design page. A test checks they exist in tokens.css. */
export const colorTokens = [
  "bg",
  "surface",
  "surface-sunken",
  "border",
  "text",
  "text-muted",
  "text-disabled",
  "text-inverse",
  "accent",
  "accent-pressed",
  "accent-soft",
  "on-accent",
  "success",
  "success-soft",
  "success-line",
  "warning",
  "warning-soft",
  "danger",
  "danger-soft",
  "focus-ring",
  "overlay",
  "avatar-1",
  "avatar-2",
  "avatar-3",
  "avatar-4",
  "avatar-5",
  "code-bg",
  "code-fg",
  "media-bg",
  "on-media",
  "media-scrim",
] as const;

export const textTokens = [
  "title-l",
  "title-m",
  "title-s",
  "body",
  "input",
  "small",
  "caption",
  "number",
] as const;
export const spaceTokens = ["1", "2", "3", "4", "5", "6", "8", "10", "12"] as const;
export const radiusTokens = ["media-inner", "sm", "md", "lg", "xl", "full"] as const;
export const shadowTokens = ["card", "sheet"] as const;
export const sizeTokens = [
  "tap-min",
  "button-height",
  "button-height-sm",
  "input-height",
  "avatar-sm",
  "avatar-md",
  "avatar-lg",
  "tabbar-height",
  "day-bar-height",
  "proof-tile-size",
  "story-avatar-size",
  "story-avatar-size-lg",
  "mini-bar-height",
] as const;
