# Generated by Django 5.2.17 on 2026-10-04 19:05

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crews", "0003_remove_rotation_and_deadline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=60)),
                ("rules", models.CharField(blank=True, max_length=500)),
                ("icon", models.CharField(default="star", max_length=20)),
                (
                    "measure",
                    models.CharField(
                        choices=[
                            ("check", "Just check in"),
                            ("quantity", "A number with a unit"),
                            ("abstain", "Held it (did not do something)"),
                        ],
                        default="check",
                        max_length=10,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Every day"),
                            ("weekdays", "Chosen days of the week"),
                            ("times_per_week", "A number of times a week"),
                            ("times_per_period", "A number of times in the period"),
                            ("once", "Once, by the end"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "weekdays",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Bit mask of chosen days: Monday = 1, Tuesday = 2, ... Sunday = 64.",
                    ),
                ),
                ("times", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "target_scope",
                    models.CharField(
                        choices=[
                            ("none", "No target"),
                            ("per_check_in", "Each check-in"),
                            ("per_week", "Each week"),
                            ("per_period", "The whole period"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "proof_kind",
                    models.CharField(
                        choices=[
                            ("none", "No proof"),
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("photo_or_video", "Photo or video"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("proof_required", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("chosen", "Chosen"),
                            ("not_chosen", "Not chosen"),
                        ],
                        default="proposed",
                        max_length=12,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "revision",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Goes up with every edit; votes are reset on each edit.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to="crews.member",
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="crews.crew",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_kind",
                    models.CharField(
                        choices=[
                            ("month", "Month"),
                            ("week", "Week"),
                            ("custom", "Custom"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        help_text="First day of the period, in the crew's time zone."
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        help_text="Last day of the period, in the crew's time zone."
                    ),
                ),
                (
                    "selection",
                    models.CharField(
                        choices=[("admin", "An admin chooses")],
                        default="admin",
                        max_length=10,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("chosen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chosen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "chosen_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crews.member",
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="crews.crew",
                    ),
                ),
            ],
            options={
                "ordering": ("period_start",),
            },
        ),
        migrations.AddField(
            model_name="challenge",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to="challenges.round",
            ),
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="crews.crew",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="crews.member",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="challenges.round",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "joined_on",
                    models.DateField(
                        help_text="First day that counts for this member."
                    ),
                ),
                (
                    "ended_on",
                    models.DateField(
                        blank=True,
                        help_text="Last day that counts, when the member left early.",
                        null=True,
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="crews.crew",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="crews.member",
                    ),
                ),
            ],
            options={
                "ordering": ("joined_on", "created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("challenge", "member"),
                        name="participation_one_per_member",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.UniqueConstraint(
                fields=("crew", "period_kind", "period_start"),
                name="round_unique_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="round_period_not_reversed",
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state", "proposed"),
                    ("state", "not_chosen"),
                    models.Q(
                        ("end_date__isnull", False), ("start_date__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="challenge_chosen_has_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("round", "member"), name="vote_one_per_member"
            ),
        ),
    ]
