# Generated by Django 5.2.17 on 2026-10-05 03:58

import django.db.models.deletion
from django.db import migrations, models


def move_period_to_challenges(apps, schema_editor):
    """Proposals leave their rounds: not chosen ones go back to the pool, chosen ones keep the
    round's period and who chose them. Votes stay (one per member and proposal already holds)."""
    Challenge = apps.get_model("challenges", "Challenge")
    for challenge in Challenge.objects.select_related("round"):
        round_ = challenge.round
        if challenge.state == "chosen":
            challenge.period_kind = round_.period_kind
            challenge.period_start = round_.period_start
            if round_.chosen_id == challenge.pk:
                challenge.chosen_by_id = round_.chosen_by_id
                challenge.chosen_at = round_.chosen_at
        else:
            challenge.state = "proposed"
            challenge.start_date = None
            challenge.end_date = None
        challenge.save()


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0001_initial"),
        ("crews", "0004_crew_max_proposals"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="challenge",
            name="challenge_chosen_has_dates",
        ),
        migrations.RemoveConstraint(
            model_name="vote",
            name="vote_one_per_member",
        ),
        migrations.AddField(
            model_name="challenge",
            name="chosen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="chosen_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="crews.member",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="period_kind",
            field=models.CharField(
                blank=True,
                choices=[("month", "Month"), ("week", "Week"), ("custom", "Custom")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="period_start",
            field=models.DateField(
                blank=True,
                help_text="First day of the period (the 1st for a month).",
                null=True,
            ),
        ),
        migrations.RunPython(move_period_to_challenges, elidable=False),
    ]
