# Generated by Django 5.2.17 on 2026-10-05 06:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


def invite_the_whole_crew(apps, schema_editor):
    """Challenges made before invitees existed keep their old rule: the whole crew takes part."""
    Challenge = apps.get_model("challenges", "Challenge")
    Invitee = apps.get_model("challenges", "Invitee")
    Member = apps.get_model("crews", "Member")
    rows = []
    for challenge in Challenge.objects.all():
        for member_id in Member.objects.filter(crew_id=challenge.crew_id).values_list("pk", flat=True):
            rows.append(
                Invitee(
                    id=uuid.uuid4(),
                    crew_id=challenge.crew_id,
                    challenge_id=challenge.pk,
                    member_id=member_id,
                )
            )
    Invitee.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0003_remove_rounds"),
        ("crews", "0004_crew_max_proposals"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitees",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="crews.crew",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invited_to",
                        to="crews.member",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("challenge", "member"), name="invitee_once_per_member"
                    )
                ],
            },
        ),
        migrations.RunPython(invite_the_whole_crew, migrations.RunPython.noop),
    ]
