# Generated by Django 5.2.17 on 2026-10-08 05:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0014_proof_yes_or_no'),
        ('crews', '0004_crew_max_proposals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(help_text='1 to 8: its number on the dial.')),
                ('text', models.CharField(max_length=80)),
                ('proof_required', models.BooleanField(default=False, help_text='Served with a photo or a video; else by tapping Done.')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishments', to='challenges.challenge')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crews.crew')),
            ],
            options={
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('challenge', 'position'), name='punishment_position_once'), models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 8)), name='punishment_position_1_to_8')],
            },
        ),
    ]
