/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/v1/auth/csrf - sets the csrftoken cookie; call it before the first POST. */
        get: operations["auth_csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/v1/auth/login - starts a session. Then call GET /api/v1/me. */
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/v1/auth/logout - ends the session. */
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The crew the user is acting in, with its members in the order they joined. */
        get: operations["crew_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crew/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Admin: the crew's pending invites, and creating a single-use invite valid for 7 days. */
        get: operations["crew_invites_list"];
        put?: never;
        /** @description Admin: the crew's pending invites, and creating a single-use invite valid for 7 days. */
        post: operations["crew_invites_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crew/invites/{invite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Admin: cancel an invite nobody has used yet. */
        delete: operations["crew_invites_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invites/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public: what the join page shows before the person signs up. */
        get: operations["invites_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invites/{code}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Public: create an account from an invite, join the crew, and log in. */
        post: operations["invites_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invites/{code}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Logged in: join the invite's crew with the account you already have. */
        post: operations["invites_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The logged-in user, their membership and crew (member and crew are null outside a crew). */
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description The logged-in user, their membership and crew (member and crew are null outside a crew). */
        patch: operations["me_update"];
        trace?: never;
    };
    "/api/v1/me/crew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Switch the crew the user acts in (for people in several crews). */
        put: operations["me_crew_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptInviteInRequest: {
            username: string;
            password: string;
            display_name: string;
            /**
             * @description The language used to sign up.
             *
             *     * `ro` - Romana
             *     * `en` - English
             */
            preferred_language?: components["schemas"]["PreferredLanguageEnum"];
        };
        ActiveCrewInRequest: {
            /** Format: uuid */
            crew_id: string;
        };
        CrewDetailOut: {
            /** Format: uuid */
            id: string;
            name: string;
            timezone: string;
            /** @description In the order they joined. */
            members: components["schemas"]["MemberOut"][];
        };
        CrewOut: {
            /** Format: uuid */
            id: string;
            name: string;
            timezone: string;
        };
        CsrfOut: {
            csrf_token: string;
        };
        InviteOut: {
            code: string;
            /** Format: uri */
            url: string;
            /** Format: date-time */
            expires_at: string;
        };
        InvitePreviewOut: {
            crew_name: string;
            status: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            expires_at: string;
            /** @description Who created the invite. Only for valid invites. */
            invited_by: components["schemas"]["MemberSummaryOut"] | null;
            /** @description Members in the order they joined. Empty unless the invite is valid. */
            members: components["schemas"]["MemberSummaryOut"][];
            /** @description True when the logged-in user is already in this crew. */
            already_member: boolean;
            /**
             * Format: uuid
             * @description The crew's id, only for its own members (to switch to it).
             */
            crew_id: string | null;
        };
        JoinWithAccountInRequest: {
            display_name: string;
        };
        LoginInRequest: {
            username: string;
            password: string;
        };
        MeOut: {
            user: components["schemas"]["UserOut"];
            member: components["schemas"]["MemberOut"] | null;
            crew: components["schemas"]["CrewOut"] | null;
            /** @description Every crew the user belongs to, by name. */
            crews: components["schemas"]["MembershipOut"][];
        };
        MemberOut: {
            /** Format: uuid */
            id: string;
            display_name: string;
            role: string;
            avatar_seed: string;
        };
        MemberSummaryOut: {
            display_name: string;
            avatar_seed: string;
        };
        MembershipOut: {
            /** Format: uuid */
            crew_id: string;
            crew_name: string;
            display_name: string;
            role: string;
        };
        PatchedMePatchInRequest: {
            display_name?: string;
            preferred_language?: components["schemas"]["PreferredLanguageEnum"];
        };
        PendingInviteOut: {
            code: string;
            /** Format: uri */
            url: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: uuid */
            id: string;
            created_by: components["schemas"]["MemberSummaryOut"] | null;
        };
        /**
         * @description * `ro` - Romana
         *     * `en` - English
         * @enum {string}
         */
        PreferredLanguageEnum: "ro" | "en";
        /**
         * @description * `valid` - valid
         *     * `expired` - expired
         *     * `used` - used
         * @enum {string}
         */
        StatusEnum: "valid" | "expired" | "used";
        UserOut: {
            /** Format: uuid */
            id: string;
            username: string;
            preferred_language: components["schemas"]["PreferredLanguageEnum"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfOut"];
                };
            };
        };
    };
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    crew_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrewDetailOut"];
                };
            };
        };
    };
    crew_invites_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingInviteOut"][];
                };
            };
        };
    };
    crew_invites_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"];
                };
            };
        };
    };
    crew_invites_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    invites_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitePreviewOut"];
                };
            };
        };
    };
    invites_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteInRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    invites_join: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinWithAccountInRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMePatchInRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    me_crew_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActiveCrewInRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
}
