/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/v1/auth/csrf - sets the csrftoken cookie; call it before the first POST. */
        get: operations["auth_csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/v1/auth/login - starts a session. Then call GET /api/v1/me. */
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/v1/auth/logout - ends the session. */
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Scheduled challenges, by start date. */
        get: operations["challenges_list"];
        put?: never;
        /** @description Add a proposal to the crew's pool (409 pool_full when it is full). */
        post: operations["challenges_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/challenges/{challenge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["challenges_retrieve"];
        /** @description The creator replaces their proposal while it is in the pool. Resets its votes. */
        put: operations["challenges_update"];
        post?: never;
        /** @description The creator or an admin withdraws a proposal from the pool. */
        delete: operations["challenges_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/challenges/{challenge_id}/participation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Take part again (before the start). */
        put: operations["challenges_take_part"];
        post?: never;
        /** @description Opt out before the start, or leave a running challenge from tomorrow. */
        delete: operations["challenges_opt_out"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/challenges/{challenge_id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Admin: schedule a proposal for a period, or move it before it starts. */
        put: operations["challenges_schedule"];
        post?: never;
        /** @description Admin: put a scheduled challenge back in the pool before it starts. */
        delete: operations["challenges_unschedule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/challenges/{challenge_id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Vote for a proposal (voting twice counts once). */
        put: operations["challenges_vote"];
        post?: never;
        /** @description Take your vote back. */
        delete: operations["challenges_vote_clear"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The crew the user is acting in, with its members in the order they joined. */
        get: operations["crew_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crew/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Admin: the crew's pending invites, and creating a single-use invite valid for 7 days. */
        get: operations["crew_invites_list"];
        put?: never;
        /** @description Admin: the crew's pending invites, and creating a single-use invite valid for 7 days. */
        post: operations["crew_invites_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crew/invites/{invite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Admin: cancel an invite nobody has used yet. */
        delete: operations["crew_invites_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invites/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public: what the join page shows before the person signs up. */
        get: operations["invites_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invites/{code}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Public: create an account from an invite, join the crew, and log in. */
        post: operations["invites_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invites/{code}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Logged in: join the invite's crew with the account you already have. */
        post: operations["invites_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The logged-in user, their membership and crew (member and crew are null outside a crew). */
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description The logged-in user, their membership and crew (member and crew are null outside a crew). */
        patch: operations["me_update"];
        trace?: never;
    };
    "/api/v1/me/crew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Switch the crew the user acts in (for people in several crews). */
        put: operations["me_crew_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The crew's pool of proposals, newest first, with votes and how full it is. */
        get: operations["proposals_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptInviteInRequest: {
            username: string;
            password: string;
            display_name: string;
            /**
             * @description The language used to sign up.
             *
             *     * `ro` - Romana
             *     * `en` - English
             */
            preferred_language?: components["schemas"]["PreferredLanguageEnum"];
        };
        ActiveCrewInRequest: {
            /** Format: uuid */
            crew_id: string;
        };
        ChallengeDetailOut: {
            /** Format: uuid */
            id: string;
            title: string;
            rules: string;
            icon: components["schemas"]["IconEnum"];
            measure: components["schemas"]["MeasureEnum"];
            unit: string;
            frequency: components["schemas"]["FrequencyEnum"];
            weekdays: number[];
            times: number | null;
            target_scope: components["schemas"]["TargetScopeEnum"];
            /** Format: double */
            target_value: number | null;
            proof_kind: components["schemas"]["ProofKindEnum"];
            proof_required: boolean;
            state: components["schemas"]["ChallengeStateEnum"];
            phase: (components["schemas"]["PhaseEnum"] | components["schemas"]["NullEnum"]) | null;
            period_kind: (components["schemas"]["PeriodKindEnum"] | components["schemas"]["NullEnum"]) | null;
            /** Format: date */
            period_start: string | null;
            /** Format: date */
            start_date: string | null;
            /** Format: date */
            end_date: string | null;
            chosen_by: components["schemas"]["PersonOut"] | null;
            /** Format: date-time */
            chosen_at: string | null;
            created_by: components["schemas"]["PersonOut"] | null;
            /** Format: date-time */
            created_at: string;
            revision: number;
            vote_count: number;
            voters: components["schemas"]["PersonOut"][];
            /** @description The current member voted for it. */
            my_vote: boolean;
            /** @description Proposed by the current member. */
            mine: boolean;
            participants: components["schemas"]["ParticipantOut"][];
            /** @description The current member counts in it today. */
            taking_part: boolean;
        };
        /** @description The creator's choices. Combinations are checked in services.clean_shape. */
        ChallengeInRequest: {
            title: string;
            /** @default  */
            rules: string;
            /** @default star */
            icon: components["schemas"]["IconEnum"];
            measure: components["schemas"]["MeasureEnum"];
            /** @default  */
            unit: string;
            frequency: components["schemas"]["FrequencyEnum"];
            /** @description For frequency=weekdays: 0 = Monday ... 6 = Sunday. */
            weekdays?: number[];
            times?: number | null;
            /** @default none */
            target_scope: components["schemas"]["TargetScopeEnum"];
            /** Format: decimal */
            target_value?: string | null;
            /** @default none */
            proof_kind: components["schemas"]["ProofKindEnum"];
            /** @default false */
            proof_required: boolean;
        };
        ChallengeOut: {
            /** Format: uuid */
            id: string;
            title: string;
            rules: string;
            icon: components["schemas"]["IconEnum"];
            measure: components["schemas"]["MeasureEnum"];
            unit: string;
            frequency: components["schemas"]["FrequencyEnum"];
            weekdays: number[];
            times: number | null;
            target_scope: components["schemas"]["TargetScopeEnum"];
            /** Format: double */
            target_value: number | null;
            proof_kind: components["schemas"]["ProofKindEnum"];
            proof_required: boolean;
            state: components["schemas"]["ChallengeStateEnum"];
            phase: (components["schemas"]["PhaseEnum"] | components["schemas"]["NullEnum"]) | null;
            period_kind: (components["schemas"]["PeriodKindEnum"] | components["schemas"]["NullEnum"]) | null;
            /** Format: date */
            period_start: string | null;
            /** Format: date */
            start_date: string | null;
            /** Format: date */
            end_date: string | null;
            chosen_by: components["schemas"]["PersonOut"] | null;
            /** Format: date-time */
            chosen_at: string | null;
            created_by: components["schemas"]["PersonOut"] | null;
            /** Format: date-time */
            created_at: string;
            revision: number;
            vote_count: number;
            voters: components["schemas"]["PersonOut"][];
            /** @description The current member voted for it. */
            my_vote: boolean;
            /** @description Proposed by the current member. */
            mine: boolean;
        };
        /**
         * @description * `proposed` - Proposed
         *     * `chosen` - Chosen
         * @enum {string}
         */
        ChallengeStateEnum: "proposed" | "chosen";
        CrewDetailOut: {
            /** Format: uuid */
            id: string;
            name: string;
            timezone: string;
            /** @description In the order they joined. */
            members: components["schemas"]["MemberOut"][];
        };
        CrewOut: {
            /** Format: uuid */
            id: string;
            name: string;
            timezone: string;
        };
        CsrfOut: {
            csrf_token: string;
        };
        /**
         * @description * `daily` - Every day
         *     * `weekdays` - Chosen days of the week
         *     * `times_per_week` - A number of times a week
         *     * `times_per_period` - A number of times in the period
         *     * `once` - Once, by the end
         * @enum {string}
         */
        FrequencyEnum: "daily" | "weekdays" | "times_per_week" | "times_per_period" | "once";
        /**
         * @description * `dumbbell` - dumbbell
         *     * `running` - running
         *     * `book` - book
         *     * `water` - water
         *     * `sugar` - sugar
         *     * `phone` - phone
         *     * `sleep` - sleep
         *     * `walk` - walk
         *     * `meditate` - meditate
         *     * `food` - food
         *     * `money` - money
         *     * `star` - star
         * @enum {string}
         */
        IconEnum: "dumbbell" | "running" | "book" | "water" | "sugar" | "phone" | "sleep" | "walk" | "meditate" | "food" | "money" | "star";
        InviteOut: {
            code: string;
            /** Format: uri */
            url: string;
            /** Format: date-time */
            expires_at: string;
        };
        InvitePreviewOut: {
            crew_name: string;
            status: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            expires_at: string;
            /** @description Who created the invite. Only for valid invites. */
            invited_by: components["schemas"]["MemberSummaryOut"] | null;
            /** @description Members in the order they joined. Empty unless the invite is valid. */
            members: components["schemas"]["MemberSummaryOut"][];
            /** @description True when the logged-in user is already in this crew. */
            already_member: boolean;
            /**
             * Format: uuid
             * @description The crew's id, only for its own members (to switch to it).
             */
            crew_id: string | null;
        };
        JoinWithAccountInRequest: {
            display_name: string;
        };
        LoginInRequest: {
            username: string;
            password: string;
        };
        MeOut: {
            user: components["schemas"]["UserOut"];
            member: components["schemas"]["MemberOut"] | null;
            crew: components["schemas"]["CrewOut"] | null;
            /** @description Every crew the user belongs to, by name. */
            crews: components["schemas"]["MembershipOut"][];
        };
        /**
         * @description * `check` - Just check in
         *     * `quantity` - A number with a unit
         *     * `abstain` - Held it (did not do something)
         * @enum {string}
         */
        MeasureEnum: "check" | "quantity" | "abstain";
        MemberOut: {
            /** Format: uuid */
            id: string;
            display_name: string;
            role: string;
            avatar_seed: string;
        };
        MemberSummaryOut: {
            display_name: string;
            avatar_seed: string;
        };
        MembershipOut: {
            /** Format: uuid */
            crew_id: string;
            crew_name: string;
            display_name: string;
            role: string;
        };
        /** @enum {unknown} */
        NullEnum: null;
        ParticipantOut: {
            member: components["schemas"]["PersonOut"];
            /** Format: date */
            joined_on: string;
            /** Format: date */
            ended_on: string | null;
        };
        PatchedMePatchInRequest: {
            display_name?: string;
            preferred_language?: components["schemas"]["PreferredLanguageEnum"];
        };
        PendingInviteOut: {
            code: string;
            /** Format: uri */
            url: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: uuid */
            id: string;
            created_by: components["schemas"]["MemberSummaryOut"] | null;
        };
        /**
         * @description * `month` - Month
         *     * `week` - Week
         *     * `custom` - Custom
         * @enum {string}
         */
        PeriodKindEnum: "month" | "week" | "custom";
        PersonOut: {
            /** Format: uuid */
            id: string;
            display_name: string;
            avatar_seed: string;
        };
        /**
         * @description * `upcoming` - upcoming
         *     * `active` - active
         *     * `finished` - finished
         * @enum {string}
         */
        PhaseEnum: "upcoming" | "active" | "finished";
        PoolOut: {
            /** @description Newest first. */
            proposals: components["schemas"]["ChallengeOut"][];
            /** @description Proposals in the pool. */
            size: number;
            /** @description How many the pool can hold (Crew.max_proposals). */
            limit: number;
        };
        /**
         * @description * `ro` - Romana
         *     * `en` - English
         * @enum {string}
         */
        PreferredLanguageEnum: "ro" | "en";
        /**
         * @description * `none` - No proof
         *     * `photo` - Photo
         *     * `video` - Video
         *     * `photo_or_video` - Photo or video
         * @enum {string}
         */
        ProofKindEnum: "none" | "photo" | "video" | "photo_or_video";
        ScheduleInRequest: {
            period_kind: components["schemas"]["PeriodKindEnum"];
            /**
             * Format: date
             * @description First day of the period (the 1st for a month).
             */
            period_start: string;
        };
        /**
         * @description * `valid` - valid
         *     * `expired` - expired
         *     * `used` - used
         * @enum {string}
         */
        StatusEnum: "valid" | "expired" | "used";
        /**
         * @description * `none` - No target
         *     * `per_check_in` - Each check-in
         *     * `per_week` - Each week
         *     * `per_period` - The whole period
         * @enum {string}
         */
        TargetScopeEnum: "none" | "per_check_in" | "per_week" | "per_period";
        UserOut: {
            /** Format: uuid */
            id: string;
            username: string;
            preferred_language: components["schemas"]["PreferredLanguageEnum"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfOut"];
                };
            };
        };
    };
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    challenges_list: {
        parameters: {
            query?: {
                /** @description Comma-separated: upcoming, active, finished. Default: all three. */
                phase?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeOut"][];
                };
            };
        };
    };
    challenges_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChallengeInRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeOut"];
                };
            };
        };
    };
    challenges_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeDetailOut"];
                };
            };
        };
    };
    challenges_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChallengeInRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeOut"];
                };
            };
        };
    };
    challenges_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    challenges_take_part: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeDetailOut"];
                };
            };
        };
    };
    challenges_opt_out: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    challenges_schedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleInRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeDetailOut"];
                };
            };
        };
    };
    challenges_unschedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    challenges_vote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeOut"];
                };
            };
        };
    };
    challenges_vote_clear: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    crew_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrewDetailOut"];
                };
            };
        };
    };
    crew_invites_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingInviteOut"][];
                };
            };
        };
    };
    crew_invites_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"];
                };
            };
        };
    };
    crew_invites_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    invites_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitePreviewOut"];
                };
            };
        };
    };
    invites_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteInRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    invites_join: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinWithAccountInRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMePatchInRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    me_crew_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActiveCrewInRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    proposals_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolOut"];
                };
            };
        };
    };
}
