# Generated by Django 5.2.17 on 2026-10-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='post_id',
            field=models.UUIDField(blank=True, db_index=True, help_text="The post that published it (a check-in's entry, a served spin); empty: a draft.", null=True),
        ),
    ]
