# Generated by Django 5.2.17 on 2026-10-08 05:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0015_punishments'),
        ('crews', '0004_crew_max_proposals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('window_first', models.DateField(help_text='The failed window it came from.')),
                ('window_last', models.DateField()),
                ('number', models.PositiveSmallIntegerField(help_text='1, 2... within its window.')),
                ('need', models.DecimalField(decimal_places=2, help_text='What the window asked.', max_digits=10)),
                ('done', models.DecimalField(decimal_places=2, help_text='What was done in it.', max_digits=12)),
                ('drawn_at', models.DateTimeField(blank=True, null=True)),
                ('serve_by', models.DateField(blank=True, help_text="The draw's crew-local day + 7.", null=True)),
                ('done_at', models.DateTimeField(blank=True, help_text='"Done", for a punishment that needs no proof.', null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='challenges.challenge')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crews.crew')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='crews.member')),
                ('punishment', models.ForeignKey(blank=True, help_text='Drawn on the server; empty until then.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='challenges.punishment')),
            ],
            options={
                'ordering': ('window_first', 'number'),
                'constraints': [models.UniqueConstraint(fields=('challenge', 'member', 'window_first', 'number'), name='spin_once')],
            },
        ),
    ]
