# Generated by Django 5.2.17 on 2026-10-03 21:00

import apps.crews.models
import datetime
import django.core.validators
import django.db.models.constraints
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Crew",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60)),
                (
                    "timezone",
                    models.CharField(
                        default=apps.crews.models.default_timezone,
                        help_text="IANA time zone, for example Europe/Chisinau. Challenge days follow it.",
                        max_length=64,
                        validators=[apps.crews.models.validate_timezone],
                    ),
                ),
                (
                    "proposal_deadline_day",
                    models.PositiveSmallIntegerField(
                        default=28,
                        help_text="Day of the month by which the proposer must publish the next challenge.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                    ),
                ),
                (
                    "reveal_time",
                    models.TimeField(
                        default=datetime.time(20, 0),
                        help_text="Local time on the last day of the month when the next challenge is revealed.",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("proposal_deadline_day__gte", 1),
                            ("proposal_deadline_day__lte", 28),
                        ),
                        name="crew_deadline_day_1_to_28",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=40)),
                (
                    "avatar_seed",
                    models.CharField(
                        help_text="Seed for the generated avatar.", max_length=16
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("member", "Member")],
                        default="member",
                        max_length=10,
                    ),
                ),
                (
                    "rotation_position",
                    models.PositiveSmallIntegerField(
                        help_text="Order in which members propose challenges, starting at 0."
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="crews.crew",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("crew", "rotation_position"),
            },
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=16, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "crew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="crews.crew",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites_sent",
                        to="crews.member",
                    ),
                ),
                (
                    "used_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="joined_with",
                        to="crews.member",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                fields=("crew", "user"), name="member_unique_user_per_crew"
            ),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("crew", "rotation_position"),
                name="member_unique_rotation_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("display_name"),
                models.F("crew"),
                name="member_unique_display_name_per_crew",
            ),
        ),
        migrations.AddConstraint(
            model_name="invite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("used_at__isnull", True), ("used_by__isnull", True)),
                    ("used_at__isnull", False),
                    _connector="OR",
                ),
                name="invite_used_by_requires_used_at",
            ),
        ),
    ]
