# Generated by Django 5.2.17 on 2026-10-04 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="last_active_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user last chose this crew; their most recent crew opens after login.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invites_sent",
                to="crews.member",
            ),
        ),
    ]
