# Generated by Django 5.2.17 on 2026-10-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crews", "0002_member_last_active_invite_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ("crew", "created_at")},
        ),
        migrations.RemoveConstraint(
            model_name="crew",
            name="crew_deadline_day_1_to_28",
        ),
        migrations.RemoveConstraint(
            model_name="member",
            name="member_unique_rotation_position",
        ),
        migrations.RemoveField(
            model_name="crew",
            name="proposal_deadline_day",
        ),
        migrations.RemoveField(
            model_name="crew",
            name="reveal_time",
        ),
        migrations.RemoveField(
            model_name="member",
            name="rotation_position",
        ),
    ]
