# Generated by Django 5.2.17 on 2026-10-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crews", "0003_remove_rotation_and_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="max_proposals",
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text="How many proposals the pool can hold (1-200).",
            ),
        ),
        migrations.AddConstraint(
            model_name="crew",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_proposals__gte", 1), ("max_proposals__lte", 200)
                ),
                name="crew_max_proposals_range",
            ),
        ),
    ]
