# Generated by Django 5.2.17 on 2026-10-05 17:45

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crews', '0004_crew_max_proposals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('key', models.CharField(help_text='Object key, made on the server.', max_length=255, unique=True)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField(help_text='Bytes the browser announced; checked on complete.')),
                ('fingerprint', models.CharField(blank=True, help_text='Name, size and lastModified of the file, to resume.', max_length=300)),
                ('mode', models.CharField(choices=[('single', 'One presigned PUT'), ('multipart', 'Multipart, resumable')], max_length=10)),
                ('upload_id', models.CharField(blank=True, help_text='S3 multipart upload id.', max_length=1024)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('complete', 'Complete'), ('failed', 'Failed')], default='uploading', max_length=10)),
                ('parts', models.JSONField(blank=True, default=dict, help_text='ETag of each finished part: {"1": "\\"etag\\""}.')),
                ('expires_at', models.DateTimeField(help_text='The upload must complete before this instant.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crews.crew')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
