# Generated by Django 5.2.17 on 2026-10-05 18:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0004_crew_max_proposals'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='running', max_length=10)),
                ('hls_key', models.CharField(blank=True, help_text='The master playlist.', max_length=255)),
                ('poster_key', models.CharField(blank=True, max_length=255)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crews.crew')),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcode', to='media.upload')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
