# Generated by Django 5.2.17 on 2026-10-05 08:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("challenges", "0004_invitees"),
        ("crews", "0004_crew_max_proposals"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.DateField(
                        help_text="The challenge day, in the crew's time zone."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("done", "Done"),
                            (
                                "in_progress",
                                "In progress (a number below the day's target)",
                            ),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The day's total for challenges that record a number; empty otherwise.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_ins",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="crews.crew",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_ins",
                        to="crews.member",
                    ),
                ),
            ],
            options={
                "ordering": ("day", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="CheckInEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="1, 2, 3... in the order they were added."
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "check_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="checkins.checkin",
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="crews.crew",
                    ),
                ),
            ],
            options={
                "ordering": ("number",),
            },
        ),
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(
                fields=["challenge", "day"], name="checkins_ch_challen_d083d9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="checkin",
            constraint=models.UniqueConstraint(
                fields=("challenge", "member", "day"), name="check_in_once_per_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="checkinentry",
            constraint=models.UniqueConstraint(
                fields=("check_in", "number"), name="entry_number_once"
            ),
        ),
    ]
