# Generated by Django 5.2.17 on 2026-10-05 18:42

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
        ('crews', '0004_crew_max_proposals'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing (video renditions)'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploading', max_length=12)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='checkins.checkin')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crews.crew')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.upload')),
                ('thumb', models.ForeignKey(blank=True, help_text="A small JPEG made on the phone (a video's poster frame).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.upload')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
