# Generated by Django 5.2.17 on 2026-10-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkins", "0002_proof"),
    ]

    operations = [
        migrations.AddField(
            model_name="proof",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="A video's length in seconds, read on the phone.",
                null=True,
            ),
        ),
    ]
