# Generated by Django 5.2.17 on 2026-10-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0006_fill_proof_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('in_progress', "In progress (a number below the day's target)"), ('pending', 'Pending (only draft files, nothing posted yet)')], max_length=12),
        ),
    ]
