# Generated by Django 5.2.17 on 2026-10-10 07:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0015_punishments'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('crews', '0004_crew_max_proposals'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('check_in', 'A check-in post'), ('spin', 'A spin drawn'), ('served', 'A punishment served'), ('crew_day', 'The whole crew finished the day')], max_length=16)),
                ('subject_id', models.UUIDField()),
                ('day', models.DateField(help_text='The crew-local day it sits under.')),
                ('facts', models.JSONField(default=dict, help_text='What the card says, frozen when posted.')),
                ('challenge', models.ForeignKey(blank=True, help_text="Who may see it: the challenge's people; empty: the whole crew.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='challenges.challenge')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='crews.crew')),
                ('member', models.ForeignKey(blank=True, help_text="Who did it; empty for the crew's day.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crews.member')),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['crew', '-created_at', '-id'], name='journal_page')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'subject_type', 'subject_id', 'day'), name='journal_entry_once')],
            },
        ),
    ]
